name: HTML Validation Workflow

on:
  push:
    branches:
      - '**'

jobs:
  validate-html:
    name: Validate HTML Files
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install HTML validator
      - name: Setup HTML Validator
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          npm install -g html-validator-cli

      # Step 3: Run HTML validation
      - name: Validate HTML files
        run: html-validator --file=index.html --verbose || echo "HTML validation complete"
