name: Build and Deploy Hugo Website

on:
  push:
    branches:
      - '**' # Trigger on all branches

jobs:
  build:
    name: Build and Deploy Hugo Site
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # Step 3: Build the Hugo site
      - name: Build Hugo Site
        run: hugo --minify # Minify the output for production

      # Step 4: Debugging step (list files in public, optional)
      - name: List generated files
        run: ls -R public

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Set the branch where GitHub Pages is enabled (default is 'gh-pages')
          publish_branch: gh-pages
