name: HTML and CSS Validation Workflow

on:
  push:
    branches:
      - '**'

jobs:
  validate-html-css:
    name: Validate HTML and CSS Files
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install HTML and CSS validators
      - name: Setup Validators
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          npm install -g html-validator-cli
          npm install -g stylelint

      # Step 3: Validate HTML files
      - name: Validate HTML files
        run: html-validator --file=index.html --verbose || echo "HTML validation complete"

      # Step 4: Validate CSS files
      - name: Validate CSS files
        run: stylelint "**/*.css" || echo "CSS validation complete"
